import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import '../globals.css';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const onest = Onest({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'André Ferraz',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const translations = await getMessages();

  return (
    <html lang="en">
      <body className={`${onest.className} antialiased`}>
        <NextIntlClientProvider messages={translations}>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
